import = ["~/.config/alacritty/rose-pine.toml"]
shell = "/bin/fish"
live_config_reload = true

[window]
padding.x = 10
padding.y = 0
dynamic_padding = true

[font]
normal.family = "Iosevka Nerd Font Mono"
bold.family = "Iosevka Nerd Font Mono"
italic.family = "Iosevka Nerd Font Mono"
bold_italic.family = "Iosevka Nerd Font Mono"
size = 9

[scrolling]
history = 2000

[keyboard]
bindings = [
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize"},
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize"}
]
