general.import = ["ef-dream.toml"]
general.live_config_reload = true
terminal.shell = "/bin/fish"

[window]
padding.x = 10
padding.y = 0
dynamic_padding = true

[font]
normal.family = "Iosevka Nerd Font Mono"
bold.family = "Iosevka Nerd Font Mono"
italic.family = "Iosevka Nerd Font Mono"
bold_italic.family = "Iosevka Nerd Font Mono"
size = 12

[scrolling]
history = 2000

[keyboard]
bindings = [
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize"},
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize"}
]
