[colors.primary]
background = "#232025"
foreground = "#efd5c5"

[colors.cursor]
text = "#232025"
cursor = "#f3c09a"

[colors.selection]
background = "#412f4f"
foreground = "#efd5c5"

[colors.normal]
black   = "#232025"
red     = "#e47980"
green   = "#3fc489"
yellow  = "#d09950"
blue    = "#80aadf"
magenta = "#f498c0"
cyan    = "#8fcfd0"
white   = "#efd5c5"

[colors.bright]
black   = "#8f8886"
red     = "#ff6f6f"
green   = "#51b04f"
yellow  = "#c0b24f"
blue    = "#57b0ff"
magenta = "#ffaacf"
cyan    = "#6fb3c0"
white   = "#ffffff"
